/**
 * Local-command breadcrumbs — what Claude Code shows the model when the user
 * runs a slash command that the harness handles locally (`/clear`, `/model`, a
 * panel command). Captured from CC 2.1.278 (`captures/sonnet.json`, and this
 * repo's own sessions after a `/clear`; findings §14, 2026-09-19): three
 * synthetic user messages that reach the model as consecutive bare text blocks
 * of the next user message, after the reminder stack and before the user's own
 * text —
 *
 *   <local-command-caveat>Caveat: …</local-command-caveat>\n
 *   <command-name>/model</command-name>\n
 *               <command-message>model</command-message>\n
 *               <command-args></command-args>\n
 *   <local-command-stdout>Set model to `Sonnet 5` …</local-command-stdout>\n
 *
 * (twelve-space indent on the second and third command lines, verbatim from
 * CC's `formatCommandInputTags`; stdout XML-escaped like CC's `escapeXml`, `&
 * < >` only). `/clear` carries an EMPTY stdout block and opens the new
 * conversation. The caveat tells the model not to act on any of it.
 *
 * One Code emits these through the reminder queue's `user-prepend` placement
 * (`lib/reminders.ts`): pi dispatches an extension command BEFORE its `input`
 * event fires and handles its own built-ins (`/model`, `/name`, …) before
 * either, so there is no single interception point — every One Code local
 * command is registered through `registerLocalCommand`, which announces before
 * the handler runs, and `/model` is announced from the `model_select` event by
 * the extension that persists the choice. pi built-ins we cannot see
 * (`/compact`, `/settings`, …) stay silent. The blocks are pinned in process
 * memory, not written to the session file as CC does — a `--resume` drops them.
 */

import { announceArgumentHint, type HintEmitter } from "./argument-hints.ts";
import { REMINDER_CHANNEL, type ReminderPayload } from "./reminders.ts";

/** The slice of pi's ExtensionAPI the announcer needs (its event bus). */
export interface ReminderEmitter {
	events: { emit(channel: string, data: unknown): unknown };
}

/**
 * How each breadcrumb block begins — what a first message that is NOT the
 * user's topic starts with (the session-title extension skips these, as CC's
 * REPL does before naming a session).
 */
export const LOCAL_COMMAND_TAG_PREFIXES = ["<local-command-caveat>", "<command-name>", "<command-message>", "<local-command-stdout>"] as const;

export const LOCAL_COMMAND_CAVEAT =
	"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>\n";

/** CC's `escapeXml` (utils/xml.ts): `& < >` only. */
export function escapeXml(s: string): string {
	return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export interface LocalCommand {
	/** Command name without the slash (`clear`, `model`). */
	name: string;
	/** The argument text the user typed after the name; "" when none. */
	args?: string;
	/** The command's printed result; "" (the default) is what `/clear` shows. */
	stdout?: string;
}

/** CC's `formatCommandInputTags` — the command breadcrumb, indentation included. */
export function commandInputBlock(name: string, args = ""): string {
	return `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>\n`;
}

/** CC's `<local-command-stdout>` message; the content is XML-escaped. */
export function commandStdoutBlock(stdout = ""): string {
	return `<local-command-stdout>${escapeXml(stdout)}</local-command-stdout>\n`;
}

/** The three bare text blocks a local command leaves for the model, in CC's order. */
export function localCommandBlocks(command: LocalCommand): string[] {
	return [LOCAL_COMMAND_CAVEAT, commandInputBlock(command.name, (command.args ?? "").trim()), commandStdoutBlock(command.stdout ?? "")];
}

/**
 * Tell the model a local command ran. Call it from the command's handler
 * (before a `/clear` resets the session — the queue survives `newSession()`,
 * so the breadcrumb opens the new conversation exactly as in CC).
 */
export function announceLocalCommand(pi: ReminderEmitter, command: LocalCommand): void {
	localCommandBlocks(command).forEach((text, index) => {
		// The caveat heads a RUN of commands: a second command before the next
		// prompt joins the first caveat instead of repeating it.
		const payload: ReminderPayload = { text, placement: "user-prepend", raw: true, ...(index === 0 ? { once: true } : {}) };
		pi.events.emit(REMINDER_CHANNEL, payload);
	});
}

type CommandOptions = { handler: (args: string, ctx: any) => Promise<void> | void } & Record<string, unknown>;

/**
 * `pi.registerCommand` for a One Code local command: the breadcrumb is
 * announced before the handler runs, so no command can forget it. `/clear`
 * is the one exception — it announces from the NEW session's `session_start`
 * (see clear/index.ts) and registers plainly. `argumentHint` is the prompt's
 * dim placeholder for the command's argument (lib/argument-hints.ts).
 */
export function registerLocalCommand<O extends CommandOptions>(
	pi: ReminderEmitter & HintEmitter & { registerCommand(name: string, options: O): void },
	name: string,
	options: O & { argumentHint?: string },
): void {
	const { argumentHint, ...rest } = options;
	if (argumentHint) announceArgumentHint(pi, name, argumentHint);
	pi.registerCommand(name, {
		...(rest as O),
		handler: (args: string, ctx: unknown) => {
			announceLocalCommand(pi, { name, args });
			return options.handler(args, ctx);
		},
	});
}
