import { describe, expect, it } from "vitest";
import {
	announceLocalCommand,
	commandInputBlock,
	commandStdoutBlock,
	escapeXml,
	LOCAL_COMMAND_CAVEAT,
	localCommandBlocks,
	registerLocalCommand,
} from "../../extensions/lib/local-command.ts";
import { modelSwitchStdout } from "../../extensions/model-default/index.ts";
import { REMINDER_CHANNEL } from "../../extensions/lib/reminders.ts";

describe("local-command breadcrumbs (CC 2.1.278 capture)", () => {
	it("reproduces the /model trio byte for byte", () => {
		expect(localCommandBlocks({ name: "model", stdout: "Set model to `Sonnet 5` and saved as your default for new sessions" })).toEqual([
			"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>\n",
			"<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>\n",
			"<local-command-stdout>Set model to `Sonnet 5` and saved as your default for new sessions</local-command-stdout>\n",
		]);
	});

	it("/clear carries an empty stdout block", () => {
		expect(localCommandBlocks({ name: "clear" })[2]).toBe("<local-command-stdout></local-command-stdout>\n");
		expect(LOCAL_COMMAND_CAVEAT.startsWith("<local-command-caveat>Caveat: ")).toBe(true);
	});

	it("carries trimmed args and XML-escapes stdout like CC's escapeXml (& < > only)", () => {
		expect(commandInputBlock("effort", "  high ")).toContain("<command-args>  high </command-args>");
		expect(localCommandBlocks({ name: "effort", args: "  high " })[1]).toContain("<command-args>high</command-args>");
		expect(escapeXml(`a & b < c > "d"`)).toBe(`a &amp; b &lt; c &gt; "d"`);
		expect(commandStdoutBlock("<x>")).toBe("<local-command-stdout>&lt;x&gt;</local-command-stdout>\n");
	});

	it("announces over the reminder channel as raw user-prepend blocks, in order", () => {
		const emitted: Array<[string, unknown]> = [];
		announceLocalCommand({ events: { emit: (channel: string, data: unknown) => emitted.push([channel, data]) } }, { name: "clear" });
		expect(emitted.map(([channel]) => channel)).toEqual([REMINDER_CHANNEL, REMINDER_CHANNEL, REMINDER_CHANNEL]);
		expect(emitted.map(([, payload]) => payload)).toEqual(
			localCommandBlocks({ name: "clear" }).map((text, i) => ({ text, placement: "user-prepend", raw: true, ...(i === 0 ? { once: true } : {}) })),
		);
	});

	it("the /model stdout drops the persisted claim when the settings write failed", () => {
		expect(modelSwitchStdout("Sonnet 5", true)).toBe("Set model to `Sonnet 5` and saved as your default for new sessions");
		expect(modelSwitchStdout("Sonnet 5", false)).toBe("Set model to `Sonnet 5`");
	});
});

describe("registerLocalCommand", () => {
	it("registers the command with the breadcrumb announced before the handler runs", async () => {
		const order: string[] = [];
		const registered = new Map<string, { handler: (args: string, ctx: unknown) => unknown; description?: string }>();
		const pi = {
			events: { emit: (_channel: string, data: unknown) => order.push(`emit:${(data as { text: string }).text.slice(0, 14)}`) },
			registerCommand: (name: string, options: { handler: (args: string, ctx: unknown) => unknown; description?: string }) =>
				registered.set(name, options),
		};
		registerLocalCommand(pi, "effort", { description: "d", handler: async (args: string) => void order.push(`handler:${args}`) });
		expect(registered.get("effort")?.description).toBe("d");
		await registered.get("effort")!.handler(" high", {});
		expect(order).toEqual(["emit:<local-command", "emit:<command-name>", "emit:<local-command", "handler: high"]);
	});
});
